apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: multi-container-pod
spec:
  replicas: 3
  selector:
    matchLabels:
      name: nginx
  template:
    metadata:
      name: nginx
      labels:
        name: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
        - name: nodejs-web
          image: khannedy/nodejs-web
          ports:
            - containerPort: 3000
            
---


apiVersion: v1
kind: Service
metadata:
  name: service-nginx
spec:
  selector:
    name: nginx #target label dari template replicas
  ports:
    - port: 8080
      targetPort: 80
      name: nginx
    - port: 3000
      targetPort: 3000
      name: nodejs-web


---
apiVersion: v1
kind: Pod
metadata:
  name: curl-test
spec:
  containers:
    - name: curl
      image: khannedy/nginx-curl