apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-alpine
  labels:
    app: nginx-alpine
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-alpine
  template:
    metadata:
      labels:
        app: nginx-alpine
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
          - containerPort: 80
      containers:
      - name: curl
        image: khannedy/nginx-curl
        ports:
          - containerPort: 22

---


apiVersion: v1
kind: Service
metadata:
  name: nginx1-service
spec:
  type: NodePort
  selector:
      app: nginx-alpine
  ports:
    - name: nginx
      port: 80
      targetPort: 80
      nodePort: 30020
    - name: alpine
      port: 2222
      targetPort: 22
      nodePort: 30021